# Site settings
author: Yasmine Hajaji
title: Yasmine's Blog
header-img: img/home-bg.png
email: yasminehajaji95@gmail.com
copyright_name: Yasmine Hajaji
description: > # this means to ignore newlines until "baseurl:"
  -
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  yasmine-hj

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
